export interface FinancialData {
    Current_Assets: number;
    Current_liabilities: number;
    Stockholder_Equity: number;
    Liabilities_And_StockholderEquity: number;
    Retained_Earnings: number;
    Working_capital: number;
    Liabilities: number;
    Cash: number;
    AccountsReceivable: number;
    Inventory: number;
    Current_Other_Assets: number;
    Noncurrent_Assets: number;
    Intangible_Assets: number;
    AccountsPayable: number;
    ShortTerm_Debt: number;
    LongTerm_Debt: number;
    Noncurrent_Liabilities: number;
      Earning_Before_Interest_And_Taxes: number;
    Revenues: number;
    NetIncome: number;
    GrossProfit: number;
    Operating_Expenses: number;
    Nonoperating_Income: number;
    InterestExpense: number;
      NetCash_OperatingActivities: number;
    NetCash_InvestingActivities: number;
    NetCash_FinancingActivities: number;
  }